add_subdirectory(21_spinlock)
add_subdirectory(22_seqlock)
add_subdirectory(23_ring_buffer_spsc)
add_subdirectory(24_thread_pool)
add_subdirectory(27_ring_buffer_mpmc)
add_subdirectory(28_lockfree_stack)
add_subdirectory(29_object_pool)
add_subdirectory(30_symbol_table)
add_subdirectory(25_semaphore)
add_subdirectory(26_spin_barrier)
add_subdirectory(31_mcs_lock)
add_subdirectory(32_serial_executor)
